Update ec2_deploy.yml

diff --git a/.github/workflows/ec2_deploy.yml b/.github/workflows/ec2_deploy.yml
--- a/.github/workflows/ec2_deploy.yml
+++ b/.github/workflows/ec2_deploy.yml
@@ -50,15 +50,11 @@ jobs:
     - name: Set up SSH key
       run: |
         mkdir -p ~/.ssh
-        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
-        if [ -z "$PUBLIC_IP" ]; then
-          echo "Public IP is not set. Exiting..."
-          exit 1
-        else
-          ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$PUBLIC_IP 'echo "SSH connection successful"'
-        fi
+        ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
+        ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$PUBLIC_IP 'echo "SSH connection successful"'
+
 
     - name: Build, Tag, and Smoke Test Docker Image on EC2
       env:
