Update ec2_deploy.yml

diff --git a/.github/workflows/ec2_deploy.yml b/.github/workflows/ec2_deploy.yml
--- a/.github/workflows/ec2_deploy.yml
+++ b/.github/workflows/ec2_deploy.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - main
   schedule:
-    - cron: '0 11 * * *'  # CA 0am
+    - cron: '0 12 * * *'  # CA 0am
   workflow_dispatch:  # This line allows manual triggering of the workflow.
 
 jobs:
@@ -93,45 +93,47 @@ jobs:
     - name: Run Smoke Test
       run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$PUBLIC_IP << 'BASH_SCRIPT'
-        ENDPOINT="http://localhost:8800/books"
-        echo "Checking API endpoint: $ENDPOINT"
-        response=$(curl -s -o /dev/null -w "%{http_code}" "$ENDPOINT")
-        if [[ "$response" -ne 200 ]]; then
-          echo "Smoke test initial check failed: HTTP $response"
+        echo "Checking API endpoint: http://localhost:8800/books"
+        response=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8800/books")
+        echo "API is up. Status: HTTP $response"
+        if [ "$response" -ne "200" ]; then
+          echo "API check failed. HTTP status: $response"
           exit 1
-        else
-          echo "API is up. Status: HTTP $response"
         fi
 
         echo "Creating a new book..."
-        POST_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{"title":"Integration Test Book","description":"A book for test","price":9.99,"cover":"http://example.com/cover.jpg"}' "$ENDPOINT")
-        if [ "$POST_RESPONSE" -ne 200 ]; then
+        POST_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{"title":"Integration Test Book","description":"A book created during integration tests.","price":15.99,"cover":"http://example.com/cover.jpg"}' "http://localhost:8800/books")
+        echo "POST response code: $POST_RESPONSE"
+        if [ "$POST_RESPONSE" -ne "200" ]; then
           echo "Failed to create a book. Response code: $POST_RESPONSE"
           exit 1
         fi
 
         echo "Retrieving the list of books..."
-        BOOKS=$(curl -s "$ENDPOINT")
-        BOOK_ID=$(echo "$BOOKS" | jq -r '.[3].id')
-        echo "Retrieved Book ID: $BOOK_ID"
-
-        echo "Updating the book ID: $BOOK_ID..."
-        PUT_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Content-Type: application/json" -d '{"title":"Updated Integration Test Book","description":"Updated description.","price":18.99,"cover":"http://example.com/new_cover.jpg"}' "$ENDPOINT/$BOOK_ID")
-        if [ "$PUT_RESPONSE" -ne 200 ]; then
-          echo "Failed to update the book. Response code: $PUT_RESPONSE"
+        BOOKS=$(curl -s "http://localhost:8800/books")
+        if [[ "$BOOKS" == "[]" || "$BOOKS" == "" ]]; then
+          echo "No books found. Exiting..."
           exit 1
         fi
 
-        echo "Verifying the updates..."
-        UPDATED_BOOK=$(curl -s "$ENDPOINT/$BOOK_ID")
-        UPDATED_TITLE=$(echo "$UPDATED_BOOK" | jq -r '.title')
-        if [ "$UPDATED_TITLE" != "Updated Integration Test Book" ]; then
-          echo "Book update verification failed. Expected 'Updated Integration Test Book', got '$UPDATED_TITLE'"
+        BOOK_ID=$(echo $BOOKS | jq -r '.[0].id')
+        if [[ -z "$BOOK_ID" || "$BOOK_ID" == "null" ]]; then
+          echo "Failed to retrieve valid book ID. Exiting..."
+          exit 1
+        fi
+        echo "Retrieved Book ID: $BOOK_ID"
+
+        echo "Updating the created book..."
+        PUT_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT -H "Content-Type: application/json" -d '{"title":"Updated Integration Test Book","description":"Updated description.","price":18.99,"cover":"http://example.com/new_cover.jpg"}' "http://localhost:8800/books/$BOOK_ID")
+        echo "PUT response code: $PUT_RESPONSE"
+        if [ "$PUT_RESPONSE" -ne "200" ]; then
+          echo "Failed to update the book. Response code: $PUT_RESPONSE"
           exit 1
         fi
 
         echo "✅ Integration tests passed successfully!"
         BASH_SCRIPT
+
     
     - name: Login to Amazon ECR
       run: |
